// frontend/src/app/features/library/library.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { BooksService } from '../../core/services/books.service';

@Component({
  selector: 'app-library',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="page-header">
      <div class="page-title">Ma Bibliothèque</div>
      <button class="icon-btn" (click)="router.navigate(['/search'])">
        <i class="ti ti-plus"></i>
      </button>
    </div>

    <div class="lib-tabs">
      @for (tab of tabs; track tab.value) {
        <button class="lib-tab" [class.active]="activeTab === tab.value"
                (click)="setTab(tab.value)">
          {{ tab.label }}
          @if (getCounts()[tab.value]) {
            <span class="tab-count">{{ getCounts()[tab.value] }}</span>
          }
        </button>
      }
    </div>

    <div class="scroll-area">
      @if (loading()) {
        <div class="loading">Chargement...</div>
      } @else if (filteredBooks().length === 0) {
        <div class="empty-state">
          <span class="empty-emoji">📚</span>
          <p>Aucun livre ici</p>
          <button class="btn-secondary" (click)="router.navigate(['/search'])">
            Ajouter un livre
          </button>
        </div>
      } @else {
        @for (book of filteredBooks(); track book.id) {
          <div class="book-item">
            <div class="book-cover">{{ book.cover_emoji || '📚' }}</div>
            <div class="book-info">
              <div class="book-title">{{ book.title }}</div>
              <div class="book-author">{{ book.author }}</div>
              <div class="book-tags">
                @for (genre of book.genres?.slice(0,2); track genre) {
                  <span class="tag">{{ genre }}</span>
                }
              </div>
            </div>
            <div class="book-right">
              @if (book.rating) {
                <div class="rating">
                  <i class="ti ti-star-filled"></i>
                  {{ book.rating }}
                </div>
              }
              <button class="more-btn" (click)="openActions(book)">
                <i class="ti ti-dots-vertical"></i>
              </button>
            </div>
          </div>
        }
      }
    </div>

    @if (selectedBook()) {
      <div class="bottom-sheet-overlay" (click)="closeActions()">
        <div class="bottom-sheet" (click)="$event.stopPropagation()">
          <div class="sheet-handle"></div>
          <div class="sheet-book-title">{{ selectedBook().title }}</div>

          <div class="rating-section">
            <div class="rating-label">Note</div>
            <div class="stars-row">
              @for (star of [1,2,3,4,5]; track star) {
                <button class="star-btn" (click)="setRating(star)">
                  <i class="ti" [class.ti-star-filled]="currentRating() >= star"
                     [class.ti-star]="currentRating() < star"></i>
                </button>
              }
              <span class="rating-value">{{ currentRating() }}/5</span>
            </div>
          </div>

          <div class="sheet-actions">
            @for (status of statusOptions; track status.value) {
              <button class="sheet-btn" (click)="changeStatus(status.value)">
                <i class="ti {{ status.icon }}"></i>
                {{ status.label }}
              </button>
            }
            <button class="sheet-btn danger" (click)="removeBook()">
              <i class="ti ti-trash"></i> Retirer de ma liste
            </button>
          </div>
        </div>
      </div>
    }
  `,
  styles: [`
    .icon-btn {
      width: 38px; height: 38px;
      border-radius: 12px;
      background: var(--card);
      border: 1px solid var(--divider);
      color: var(--lavender);
      display: flex; align-items: center; justify-content: center;
      cursor: pointer;
      i { font-size: 18px; }
    }
    .lib-tabs {
      display: flex;
      background: var(--card);
      border-radius: var(--radius-md);
      padding: 4px;
      margin: 0 16px 8px;
    }
    .lib-tab {
      flex: 1; padding: 8px 4px;
      border-radius: 12px;
      font-size: 11px; text-align: center;
      cursor: pointer; border: none;
      background: none; color: var(--gray);
      font-family: 'Inter', sans-serif; font-weight: 500;
      transition: all 0.2s;
      display: flex; align-items: center; justify-content: center; gap: 4px;
      &.active { background: var(--purple); color: white; }
    }
    .tab-count {
      background: rgba(255,255,255,0.2);
      border-radius: 10px;
      padding: 0 5px;
      font-size: 9px;
    }
    .loading {
      text-align: center; padding: 40px;
      color: var(--gray); font-size: 14px;
    }
    .empty-state {
      display: flex; flex-direction: column;
      align-items: center; justify-content: center;
      padding: 60px 20px; gap: 12px;
      .empty-emoji { font-size: 48px; }
      p { color: var(--gray); font-size: 14px; }
    }
    .book-item {
      display: flex; gap: 12px;
      padding: 12px;
      background: var(--card);
      border-radius: var(--radius-md);
      margin-bottom: 8px;
      align-items: center;
      border: 1px solid var(--divider);
    }
    .book-cover {
      width: 42px; height: 58px;
      background: var(--card2);
      border-radius: 8px;
      display: flex; align-items: center; justify-content: center;
      font-size: 24px; flex-shrink: 0;
    }
    .book-info { flex: 1; min-width: 0; }
    .book-title {
      font-family: 'Poppins', sans-serif;
      font-size: 13px; font-weight: 700;
      color: var(--white);
      overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    }
    .book-author { font-size: 11px; color: var(--gray); margin-top: 2px; }
    .book-tags { display: flex; gap: 4px; margin-top: 5px; flex-wrap: wrap; }
    .book-right {
      display: flex; flex-direction: column;
      align-items: flex-end; gap: 6px; flex-shrink: 0;
    }
    .rating {
      display: flex; align-items: center; gap: 3px;
      font-size: 11px; color: var(--purple);
      i { font-size: 11px; }
    }
    .more-btn {
      background: none; border: none;
      color: var(--gray); cursor: pointer;
      i { font-size: 18px; }
    }
    .bottom-sheet-overlay {
      position: fixed; inset: 0;
      background: rgba(0,0,0,0.6);
      z-index: 200;
      display: flex; align-items: flex-end;
    }
    .bottom-sheet {
      width: 100%; max-width: 430px;
      margin: 0 auto;
      background: var(--card);
      border-radius: 24px 24px 0 0;
      padding: 12px 20px 40px;
    }
    .sheet-handle {
      width: 40px; height: 4px;
      background: var(--divider);
      border-radius: 4px;
      margin: 0 auto 16px;
    }
    .sheet-book-title {
      font-family: 'Poppins', sans-serif;
      font-weight: 700; font-size: 16px;
      color: var(--white); margin-bottom: 20px;
      text-align: center;
    }
    .rating-section { margin-bottom: 20px; }
    .rating-label { font-size: 12px; color: var(--gray); margin-bottom: 8px; }
    .stars-row {
      display: flex; align-items: center; gap: 8px;
    }
    .star-btn {
      background: none; border: none; cursor: pointer;
      i { font-size: 28px; color: var(--purple); }
      .ti-star { color: var(--gray); }
    }
    .rating-value { font-size: 13px; color: var(--gray); margin-left: 4px; }
    .sheet-actions { display: flex; flex-direction: column; gap: 8px; }
    .sheet-btn {
      padding: 14px 16px;
      background: var(--card2);
      border: 1px solid var(--divider);
      border-radius: var(--radius-md);
      color: var(--white);
      font-size: 14px; font-weight: 500;
      cursor: pointer; font-family: 'Inter', sans-serif;
      display: flex; align-items: center; gap: 10px;
      transition: background 0.18s;
      i { font-size: 18px; color: var(--lavender); }
      &.danger { color: #ff6b6b; i { color: #ff6b6b; } }
      &:active { background: var(--bg); }
    }
  `]
})
export class LibraryComponent implements OnInit {
  private booksService = inject(BooksService);
  router = inject(Router);

  tabs = [
    { label: 'À lire', value: 'to_read' },
    { label: 'En cours', value: 'reading' },
    { label: 'Lus', value: 'done' },
    { label: 'DNF', value: 'dnf' },
  ];

  statusOptions = [
    { label: 'À lire', value: 'to_read', icon: 'ti-bookmark' },
    { label: 'En cours', value: 'reading', icon: 'ti-book' },
    { label: 'Lu', value: 'done', icon: 'ti-check' },
    { label: 'Pas fini (DNF)', value: 'dnf', icon: 'ti-x' },
  ];

  activeTab = 'to_read';
  allBooks = signal<any[]>([]);
  filteredBooks = signal<any[]>([]);
  loading = signal(true);
  selectedBook = signal<any>(null);
  currentRating = signal(0);

  ngOnInit() { this.loadBooks(); }

  loadBooks() {
    this.loading.set(true);
    this.booksService.getMyBooks().subscribe({
      next: (books) => {
        this.allBooks.set(books);
        this.filterBooks();
        this.loading.set(false);
      },
      error: () => this.loading.set(false)
    });
  }

  setTab(tab: string) {
    this.activeTab = tab;
    this.filterBooks();
  }

  filterBooks() {
    this.filteredBooks.set(this.allBooks().filter(b => b.status === this.activeTab));
  }

  getCounts() {
    const counts: any = {};
    this.allBooks().forEach(b => {
      counts[b.status] = (counts[b.status] || 0) + 1;
    });
    return counts;
  }

  openActions(book: any) {
    this.selectedBook.set(book);
    this.currentRating.set(book.rating || 0);
  }

  closeActions() { this.selectedBook.set(null); }

  setRating(star: number) {
    this.currentRating.set(star);
    this.booksService.updateBook(this.selectedBook().book_id, { rating: star }).subscribe();
  }

  changeStatus(status: string) {
    this.booksService.updateBook(this.selectedBook().book_id, { status }).subscribe({
      next: () => { this.closeActions(); this.loadBooks(); }
    });
  }

  removeBook() {
    this.booksService.removeBook(this.selectedBook().book_id).subscribe({
      next: () => { this.closeActions(); this.loadBooks(); }
    });
  }
}

// app/(tabs)/library.tsx
import { useState, useCallback } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet, SafeAreaView, Alert
} from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { radius, fonts, ColorPalette } from '../../theme';
import { useTheme } from '../../context/ThemeContext';
import * as userBooks from '../../lib/userBooks';

const TABS = [
  { label: 'À lire', value: 'to_read' },
  { label: 'En cours', value: 'reading' },
  { label: 'Lus', value: 'done' },
  { label: 'DNF', value: 'dnf' },
];

export default function LibraryScreen() {
  const { colors } = useTheme();
  const router = useRouter();
  const styles = makeStyles(colors);
  const [activeTab, setActiveTab] = useState('to_read');
  const [allBooks, setAllBooks] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedBook, setSelectedBook] = useState<any>(null);

  useFocusEffect(useCallback(() => { loadBooks(); }, []));

  const loadBooks = () => {
    setLoading(true);
    userBooks.getMyBooks().then(res => { setAllBooks(res); setLoading(false); }).catch(() => setLoading(false));
  };

  const filteredBooks = allBooks.filter(b => b.status === activeTab);
  const counts: any = {};
  allBooks.forEach(b => { counts[b.status] = (counts[b.status] || 0) + 1; });

  const changeStatus = (status: string) => {
    userBooks.updateBook(selectedBook.book_id, { status }).then(() => { setSelectedBook(null); loadBooks(); });
  };

  const removeBook = () => {
    Alert.alert('Retirer', 'Retirer ce livre de ta liste ?', [
      { text: 'Annuler', style: 'cancel' },
      { text: 'Retirer', style: 'destructive', onPress: () => {
        userBooks.removeBook(selectedBook.book_id).then(() => { setSelectedBook(null); loadBooks(); });
      }}
    ]);
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Ma Bibliothèque</Text>
      </View>

      <View style={styles.tabs}>
        {TABS.map(tab => (
          <TouchableOpacity key={tab.value} style={[styles.tab, activeTab === tab.value && styles.tabActive]} onPress={() => setActiveTab(tab.value)}>
            <Text style={[styles.tabText, activeTab === tab.value && styles.tabTextActive]}>
              {tab.label}{counts[tab.value] ? ` ${counts[tab.value]}` : ''}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <ScrollView style={styles.scroll} showsVerticalScrollIndicator={false}>
        {loading ? (
          <Text style={styles.emptyText}>Chargement...</Text>
        ) : filteredBooks.length === 0 ? (
          <View style={styles.emptyState}>
            <Text style={{ fontSize: 48 }}>📚</Text>
            <Text style={styles.emptyText}>Aucun livre ici</Text>
          </View>
        ) : filteredBooks.map((book, i) => (
          <TouchableOpacity key={i} style={styles.bookItem} onPress={() => router.push(`/book/${book.book_id}`)}>
            <View style={styles.bookCover}><Text style={{ fontSize: 24 }}>📚</Text></View>
            <View style={styles.bookInfo}>
              <Text style={styles.bookTitle} numberOfLines={1}>{book.title}</Text>
              <Text style={styles.bookAuthor}>{book.author}</Text>
              <View style={styles.tags}>
                {book.format && (
                  <View style={styles.formatPill}>
                    <Text style={styles.formatPillText}>{book.format === 'physical' ? '📖 Physique' : '📱 Liseuse'}</Text>
                  </View>
                )}
                {book.genres?.slice(0, 2).map((g: string, j: number) => (
                  <View key={j} style={styles.tag}><Text style={styles.tagText}>{g}</Text></View>
                ))}
              </View>
            </View>
            <View style={styles.bookRight}>
              {book.rating ? <Text style={styles.rating}>⭐ {book.rating}</Text> : null}
              <TouchableOpacity onPress={(e) => { e.stopPropagation(); setSelectedBook(book); }}>
                <Text style={styles.moreBtn}>•••</Text>
              </TouchableOpacity>
            </View>
          </TouchableOpacity>
        ))}
        <View style={{ height: 20 }} />
      </ScrollView>

      {selectedBook && (
        <TouchableOpacity style={styles.overlay} onPress={() => setSelectedBook(null)} activeOpacity={1}>
          <TouchableOpacity style={styles.bottomSheet} activeOpacity={1}>
            <View style={styles.handle} />
            <Text style={styles.sheetTitle}>{selectedBook.title}</Text>
            {[
              { label: '🔖 À lire', value: 'to_read' },
              { label: '📖 En cours', value: 'reading' },
              { label: '✅ Lu', value: 'done' },
              { label: '❌ Pas fini (DNF)', value: 'dnf' },
            ].map(s => (
              <TouchableOpacity key={s.value} style={styles.sheetBtn} onPress={() => changeStatus(s.value)}>
                <Text style={styles.sheetBtnText}>{s.label}</Text>
              </TouchableOpacity>
            ))}
            <TouchableOpacity style={[styles.sheetBtn, styles.sheetBtnDanger]} onPress={removeBook}>
              <Text style={styles.sheetBtnDangerText}>🗑 Retirer de ma liste</Text>
            </TouchableOpacity>
          </TouchableOpacity>
        </TouchableOpacity>
      )}
    </SafeAreaView>
  );
}

const makeStyles = (colors: ColorPalette) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  header: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 4 },
  title: { fontSize: 20, fontFamily: fonts.headingBold, color: colors.white },
  tabs: { flexDirection: 'row', backgroundColor: colors.card, borderRadius: radius.md, padding: 4, marginHorizontal: 16, marginBottom: 8 },
  tab: { flex: 1, padding: 8, borderRadius: 12, alignItems: 'center' },
  tabActive: { backgroundColor: colors.purple },
  tabText: { fontSize: 11, color: colors.gray, fontWeight: '500' },
  tabTextActive: { color: 'white' },
  scroll: { flex: 1, paddingHorizontal: 16 },
  emptyState: { alignItems: 'center', paddingTop: 60, gap: 12 },
  emptyText: { color: colors.gray, fontSize: 14, textAlign: 'center', paddingTop: 40 },
  bookItem: { flexDirection: 'row', gap: 12, padding: 12, backgroundColor: colors.card, borderRadius: radius.md, marginBottom: 8, alignItems: 'center', borderWidth: 1, borderColor: colors.divider },
  bookCover: { width: 42, height: 58, backgroundColor: colors.card2, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  bookInfo: { flex: 1 },
  bookTitle: { fontSize: 13, fontWeight: '700', color: colors.white },
  bookAuthor: { fontSize: 11, color: colors.gray, marginTop: 2 },
  tags: { flexDirection: 'row', gap: 4, marginTop: 5, flexWrap: 'wrap' },
  tag: { backgroundColor: 'rgba(194,150,206,0.1)', paddingHorizontal: 7, paddingVertical: 2, borderRadius: 8 },
  tagText: { fontSize: 9, color: colors.lavender },
  formatPill: { borderWidth: 1, borderColor: colors.teal, paddingHorizontal: 7, paddingVertical: 2, borderRadius: 8 },
  formatPillText: { fontSize: 9, color: colors.teal },
  bookRight: { alignItems: 'flex-end', gap: 6 },
  rating: { fontSize: 11, color: colors.purple },
  moreBtn: { fontSize: 16, color: colors.gray },
  overlay: { position: 'absolute', inset: 0, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  bottomSheet: { backgroundColor: colors.card, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 40 },
  handle: { width: 40, height: 4, backgroundColor: colors.divider, borderRadius: 4, alignSelf: 'center', marginBottom: 16 },
  sheetTitle: { fontSize: 16, fontWeight: '700', color: colors.white, textAlign: 'center', marginBottom: 20 },
  sheetBtn: { padding: 14, backgroundColor: colors.card2, borderRadius: radius.md, marginBottom: 8, borderWidth: 1, borderColor: colors.divider },
  sheetBtnText: { color: colors.white, fontSize: 14, fontWeight: '500' },
  sheetBtnDanger: { borderColor: 'rgba(217,117,103,0.3)' },
  sheetBtnDangerText: { color: colors.error, fontSize: 14, fontWeight: '500' },
});
