// frontend/src/app/features/auth/login/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div class="auth-screen">
      <div class="auth-top">
        <div class="logo">📖 READIGMA</div>
        <div class="tagline">Stop searching. Start discovering.</div>
      </div>

      <div class="auth-card">
        <h2>Bon retour !</h2>
        <p class="subtitle">Connecte-toi pour retrouver ta pile</p>

        @if (error()) {
          <div class="error-box">{{ error() }}</div>
        }

        <div class="form-group">
          <label>Email</label>
          <input type="email" [(ngModel)]="email" placeholder="ton@email.com" />
        </div>

        <div class="form-group">
          <label>Mot de passe</label>
          <input type="password" [(ngModel)]="password" placeholder="••••••••" />
        </div>

        <button class="btn-primary" (click)="login()" [disabled]="loading()">
          @if (loading()) { Connexion... } @else { Se connecter }
        </button>

        <p class="switch-auth">
          Pas encore de compte ?
          <a routerLink="/auth/register">S'inscrire</a>
        </p>
      </div>
    </div>
  `,
  styles: [`
    .auth-screen {
      min-height: 100dvh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 24px 16px;
      background: var(--bg);
    }
    .auth-top {
      text-align: center;
      margin-bottom: 32px;
    }
    .logo {
      font-family: 'Poppins', sans-serif;
      font-weight: 700;
      font-size: 28px;
      color: var(--purple);
      letter-spacing: 1px;
    }
    .tagline {
      font-size: 13px;
      color: var(--gray);
      margin-top: 4px;
    }
    .auth-card {
      width: 100%;
      max-width: 400px;
      background: var(--card);
      border-radius: var(--radius-lg);
      border: 1px solid var(--divider);
      padding: 24px;
    }
    h2 {
      font-size: 22px;
      font-weight: 700;
      color: var(--white);
      margin-bottom: 4px;
    }
    .subtitle {
      font-size: 13px;
      color: var(--gray);
      margin-bottom: 24px;
    }
    .form-group {
      margin-bottom: 16px;
      label {
        display: block;
        font-size: 12px;
        color: var(--gray);
        margin-bottom: 6px;
        font-weight: 500;
      }
    }
    .btn-primary {
      margin-top: 8px;
      &:disabled { opacity: 0.6; }
    }
    .error-box {
      background: rgba(255, 100, 100, 0.1);
      border: 1px solid rgba(255, 100, 100, 0.3);
      color: #ff6b6b;
      padding: 10px 14px;
      border-radius: var(--radius-sm);
      font-size: 13px;
      margin-bottom: 16px;
    }
    .switch-auth {
      text-align: center;
      font-size: 13px;
      color: var(--gray);
      margin-top: 16px;
      a {
        color: var(--lavender);
        text-decoration: none;
        font-weight: 500;
      }
    }
  `]
})
export class LoginComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  email = '';
  password = '';
  loading = signal(false);
  error = signal('');

  login() {
    if (!this.email || !this.password) {
      this.error.set('Tous les champs sont requis');
      return;
    }
    this.loading.set(true);
    this.error.set('');
    this.authService.login(this.email, this.password).subscribe({
      next: () => this.router.navigate(['/discover']),
      error: (err) => {
        this.error.set(err.error?.error || 'Erreur de connexion');
        this.loading.set(false);
      }
    });
  }
}

// app/(auth)/login.tsx
import { useState } from 'react';
import {
  View, Text, TextInput, TouchableOpacity,
  StyleSheet, KeyboardAvoidingView, Platform, ScrollView, Alert
} from 'react-native';
import { Link } from 'expo-router';
import { radius, fonts, ColorPalette } from '../../theme';
import { useTheme } from '../../context/ThemeContext';
import { useAuth } from '../../context/AuthContext';

export default function LoginScreen() {
  const { colors } = useTheme();
  const { signIn } = useAuth();
  const styles = makeStyles(colors);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);

  const login = async () => {
    if (!email || !password) { Alert.alert('Erreur', 'Tous les champs sont requis'); return; }
    setLoading(true);
    try {
      await signIn(email, password);
    } catch (err: any) {
      Alert.alert('Erreur', err.message || 'Erreur de connexion');
    } finally {
      setLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView style={styles.container} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">
        <View style={styles.top}>
          <Text style={styles.logo}>📖 READIGMA</Text>
          <Text style={styles.tagline}>Stop searching. Start discovering.</Text>
        </View>

        <View style={styles.card}>
          <Text style={styles.title}>Bon retour !</Text>
          <Text style={styles.subtitle}>Connecte-toi pour retrouver ta pile</Text>

          <Text style={styles.label}>Email</Text>
          <TextInput
            style={styles.input}
            value={email}
            onChangeText={setEmail}
            placeholder="ton@email.com"
            placeholderTextColor={colors.gray}
            keyboardType="email-address"
            autoCapitalize="none"
          />

          <Text style={styles.label}>Mot de passe</Text>
          <TextInput
            style={styles.input}
            value={password}
            onChangeText={setPassword}
            placeholder="••••••••"
            placeholderTextColor={colors.gray}
            secureTextEntry
          />

          <TouchableOpacity style={styles.btn} onPress={login} disabled={loading}>
            <Text style={styles.btnText}>{loading ? 'Connexion...' : 'Se connecter'}</Text>
          </TouchableOpacity>

          <Link href="/(auth)/register" asChild>
            <TouchableOpacity>
              <Text style={styles.switchText}>
                Pas encore de compte ? <Text style={styles.switchLink}>S'inscrire</Text>
              </Text>
            </TouchableOpacity>
          </Link>
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const makeStyles = (colors: ColorPalette) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  scroll: { flexGrow: 1, justifyContent: 'center', padding: 20 },
  top: { alignItems: 'center', marginBottom: 32 },
  logo: { fontSize: 26, fontFamily: fonts.headingBold, color: colors.purple, letterSpacing: 0.5 },
  tagline: { fontSize: 13, color: colors.gray, marginTop: 4 },
  card: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  title: { fontSize: 22, fontWeight: '700', color: colors.white, marginBottom: 4 },
  subtitle: { fontSize: 13, color: colors.gray, marginBottom: 24 },
  label: { fontSize: 12, color: colors.gray, marginBottom: 6, fontWeight: '500' },
  input: {
    backgroundColor: colors.card2,
    borderRadius: radius.sm,
    padding: 14,
    color: colors.white,
    fontSize: 15,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  btn: {
    backgroundColor: colors.purple,
    borderRadius: radius.md,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  btnText: { color: 'white', fontSize: 15, fontWeight: '700' },
  switchText: { textAlign: 'center', fontSize: 13, color: colors.gray },
  switchLink: { color: colors.lavender, fontWeight: '500' },
});
